/*
 * Pin map for the PoE luminaire (ESP32 + IP101G RMII + TPS2378 + HV9910).
 *
 * Sources used to validate this mapping:
 *  - The ESP32's internal EMAC RMII pins are FIXED in hardware (unlike newer
 *    chips such as the ESP32-P4, they cannot be remapped through the IO
 *    MUX): TXD0=GPIO19, TXD1=GPIO22, TX_EN=GPIO21, RXD0=GPIO25, RXD1=GPIO26,
 *    CRS_DV=GPIO27. MDC/MDIO/RESET can be any free GPIO.
 *  - TPS2378 datasheet (TI): CDB is an open-drain, active-low output. It
 *    stays LOW during "inrush current limiting" and rises (pulled up —
 *    on this board, by the ESP32's internal software pull-up, since
 *    there's no external pull-up resistor) once the inrush current falls
 *    ~10% below the limit — the point where it's safe to enable the
 *    downstream conversion stage. This is true for real PoE of either
 *    class. T2P is an open-drain, active-low output pulled to RTN
 *    "whenever type-2 hardware classification has been observed OR the
 *    APD pin is pulled high". On this board, APD is fed by a resistor
 *    divider off the AUX bench-power input (see VLED/AUX notes below),
 *    which reads high whenever AUX is above ~40V — so T2P asserted means
 *    either real Type-2 PoE, or the AUX supply being present. See
 *    main/poe_negotiator.h for how CDB and T2P combine into the "ready"
 *    decision.
 *    https://www.mouser.com/datasheet/2/405/tps2378-447943.pdf
 *  - HV9910/B/C (Microchip/Supertex): the PWMD pin acts both as the
 *    dimming PWM input and as the power-stage enable.
 *    https://ww1.microchip.com/downloads/aemDocuments/documents/OTH/ProductDocuments/DataSheets/HV9910C-Data-Sheet-DS20005323.pdf
 *  - IP101G (IC Plus) datasheet, section 5.2 "PHY Address Configuration",
 *    Table 4: see ETH_PHY_ADDR below for how the address was derived from
 *    the board's actual strap resistors.
 *    https://www.bdtic.com/DataSheet/ICplus/IP101G_DS_R01_20121224.pdf
 */
#pragma once

#include "driver/gpio.h"

/* ---------------- Bus/LED voltage sensing (input-only pins / ADC1) ----------------
 * ADC_VLED_P also doubles as the DC bus voltage sense (VBUS) — see
 * main/voltage_sense.h.
 */
#define PIN_ADC_VLED_P          GPIO_NUM_34   /* ADC1_CH6 */
#define PIN_ADC_VLED_N          GPIO_NUM_35   /* ADC1_CH7 */

/* ---------------- HV9910 LED driver control ---------------- */
#define PIN_HV9910_SHUTDOWN     GPIO_NUM_32   /* "1:1 logic", no external inversion */
#define PIN_HV9910_DIMMING      GPIO_NUM_33   /* PWM, with external inversion (inverted logic) */

/* ---------------- IP101G PHY (RMII) ----------------
 * RXD0/RXD1/CRS_DV/TXD0/TXD1/TX_EN are fixed in the ESP32's silicon and
 * cannot be moved. Listed here purely for documentation/design review.
 */
#define PIN_ETH_RXD0             GPIO_NUM_25
#define PIN_ETH_RXD1             GPIO_NUM_26
#define PIN_ETH_CRS_DV           GPIO_NUM_27  /* "RXDV" in the original pin list */
#define PIN_ETH_TXD0             GPIO_NUM_19
#define PIN_ETH_TXD1             GPIO_NUM_22
#define PIN_ETH_TX_EN            GPIO_NUM_21
#define PIN_ETH_REF_CLK          GPIO_NUM_0   /* 50MHz clock generated by the IP101G, input on the ESP32 */
#define PIN_ETH_MDC              GPIO_NUM_23
#define PIN_ETH_MDIO             GPIO_NUM_18
#define PIN_ETH_PHY_RESET        GPIO_NUM_5   /* active-low reset, driven by the esp_eth driver */

/* ---------------- TPS2378 PoE negotiator ---------------- */
#define PIN_POE_CDB              GPIO_NUM_15  /* open-drain, no external pull-up on this board — pulled up in software, see poe_negotiator_init(). HIGH = real PoE (Type-1 or Type-2) negotiated. */
#define PIN_POE_T2P              GPIO_NUM_2   /* open-drain, no external pull-up on this board — pulled up in software, see poe_negotiator_init(). LOW = Type-2 PoE OR the AUX (>40V) bench supply is present. */
/*
 * GPIO2 (T2P) and GPIO0 (PHY clock) are also ESP32 strapping pins (they
 * select the boot mode at reset). The software pull-up on T2P (enabled at
 * runtime, after the boot-mode strapping window has already passed) and
 * the IP101G's 50MHz clock on GPIO0 are the same general pattern used in
 * Espressif's own RMII Ethernet examples, but it's worth testing a cold
 * power-on (not just a reset button press) on the final board to make
 * sure neither one forces the ESP32 into download mode.
 */

/* ---------------- Indicator LEDs ---------------- */
#define PIN_LED_STATUS           GPIO_NUM_14  /* Indicator LED 1 (overall status / heartbeat) */
#define PIN_LED_POE_WAIT         GPIO_NUM_12  /* Indicator LED 2, red: waiting for PoE negotiation */

/*
 * WARNING: GPIO12 is an ESP32 strapping pin (MTDI), used to select the
 * flash voltage (VDD_SDIO) at reset. If there's a strong external pull-up
 * on this pin (because of LED2), confirm the module/flash in use is 3.3V
 * and that boot still works normally (MTDI must read LOW or floating at
 * that reset for VDD_SDIO=3.3V, which is the default on WROOM/WROVER
 * modules). Test boot behavior before trusting the final board.
 */

/* =====================================================================
 * Application configuration parameters — all compile-time here, on
 * purpose (nothing in Kconfig/menuconfig). To change any of these values,
 * edit this file and rebuild.
 * ===================================================================== */

/* ---------------- TCP command server ---------------- */
#define APP_TCP_PORT              5000

/* ---------------- HV9910 polarity ----------------
 * CONFIRMED on the bench (2026-08-18, via ON/OFF and DIM commands over
 * the TCP command server):
 *
 *  - HV9910_SHUTDOWN_ACTIVE_HIGH = 0: GPIO32 is DIRECT logic (no external
 *    inversion) — GPIO HIGH (1) = HV9910 SHUTDOWN/enable pin HIGH = driver
 *    ENABLED. So the ASSERT (safe/off) level is LOW, and the RUN (on)
 *    level is HIGH. (Confirmed by observation: with the old, opposite
 *    setting, ON turned the driver off and OFF turned it on.)
 *  - HV9910_DIM_ACTIVE_HIGH = 1: there IS electrical inversion between
 *    GPIO33 and the HV9910's PWMD pin. The LEDC driver compensates for
 *    this via output_invert, so 0% in firmware always means "off" and
 *    100% means max brightness, regardless of the interface electronics.
 *    (Confirmed by observation: with the old, opposite setting, DIM 99
 *    produced ~1% brightness and DIM 1 produced ~99% brightness.)
 */
#define HV9910_SHUTDOWN_ACTIVE_HIGH   0
#define HV9910_DIM_ACTIVE_HIGH        1

/* PWM dimming frequency applied to the DIMMING/PWMD pin.
 * Typical range: a few hundred Hz to a few kHz, well below the HV9910's
 * internal switching frequency. Adjust if there's visible flicker or
 * audible inductor noise. */
#define HV9910_PWM_FREQ_HZ        10000

/* ---------------- IP101G PHY ----------------
 * SMI address (PHY_AD), calculated from the board's actual strap: PHY_AD0
 * pulled up (=1) and PHY_AD3 pulled down (=0). This matches the 32-pin
 * package (IP101GR/GRI — only PHY_AD0 and PHY_AD3 physically exist as pins
 * on that package; PHY_AD1/AD2 aren't even external pins on it). Per
 * Table 4 ("PHY Address Configuration") of the IC Plus IP101G-DS-R01
 * datasheet: with PHY_AD0=1, the address is FIXED at 5'd1, regardless of
 * PHY_AD3's value ("X", don't care on that row). Hence: address = 1.
 * https://www.bdtic.com/DataSheet/ICplus/IP101G_DS_R01_20121224.pdf (section 5.2)
 */
#define ETH_PHY_ADDR               1

/* ---------------- VBUS/VLED sense resistor divider ----------------
 * Both ADC_VLED_P and ADC_VLED_N go through the same resistor divider
 * before reaching the ESP32 pin: Rup=560k to the sensed node, Rdown=22k to
 * ground, ADC reads the voltage across Rdown. Scale factor to recover the
 * actual node voltage from the pin voltage: (Rup+Rdown)/Rdown.
 */
#define VLED_DIVIDER_RUP_OHM      560000.0f
#define VLED_DIVIDER_RDOWN_OHM     22000.0f
#define VLED_DIVIDER_RATIO       ((VLED_DIVIDER_RUP_OHM + VLED_DIVIDER_RDOWN_OHM) / VLED_DIVIDER_RDOWN_OHM)

/* ---------------- VBUS minimum threshold ----------------
 * Minimum DC bus voltage (VBUS, measured via ADC_VLED_P through the
 * divider above) required to trust that the system is genuinely powered.
 * Matches the same ~40V threshold the AUX sense divider uses to force the
 * TPS2378's APD pin (see the PIN_POE_T2P comment above): below this, even
 * if CDB/T2P digitally claim PoE or AUX is present, the actual bus rail
 * doesn't back that up, so poe_negotiator keeps the system in low-power
 * mode and reports why. See main/poe_negotiator.h.
 */
#define VBUS_MIN_MV                40000
